# Ruff configuration for linting
# Enable unused variable and function warnings

[lint]
# Enable all rule categories
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes (includes unused imports F401, unused variables F841, unused functions)
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
]

# Ignore specific rules if needed
ignore = [
    "E501",  # line too long (handled by formatter)
    "W191",  # indentation contains tabs (handled by formatter)
]

# The "F" category automatically includes:
# - F401: unused imports
# - F841: unused variables
# - And other pyflakes rules for unused code

# Maximum line length
line-length = 120

# Target Python version
target-version = "py313"

[format]
# Use single quotes
quote-style = "single"

# Indent with spaces
indent-style = "space"

